# Cloud Build Configuration for Tarsify API
# Triggered on push to main branch

steps:
  # Run tests
  - name: 'node:20-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install --frozen-lockfile
        pnpm test

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tarsify-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tarsify-api:latest'
      - '.'

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/tarsify-api'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tarsify-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tarsify-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '60s'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/tarsify-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tarsify-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
